coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 1%

flag_management:
  individual_flags:
    - name: python
      paths:
        - backend/
      carryforward: true
    - name: javascript
      paths:
        - frontend/
      carryforward: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "backend/*/migrations/*"
  - "backend/staticfiles/*"
  - "backend/htmlcov/*"
  - "backend/coalition/core/settings.py"
  - "frontend/build/*"
  - "frontend/coverage/*"
  - "frontend/.next/*"
  - "frontend/node_modules/*"
  - "terraform/.terraform/*"
  - "**/*_test.go"
  - "**/*.test.js"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/tests/*"
  - "**/test_*.py"
  - "**/*_tests.py"
  - "**/tests.py"
  - "**/management/commands/*"
