# Development overrides for docker-compose.yml
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d

services:
  api:
    build:
      target: deps # Use development build stage
    environment:
      - DEBUG=True # Override to enable debug mode
    volumes:
      - ./backend:/app/backend
      - ./frontend/build:/app/frontend/build:ro
    command: ["python", "/app/backend/manage.py", "runserver", "0.0.0.0:8000"]

  ssr:
    build:
      target: deps # Use development build stage
    environment:
      - NODE_ENV=development # Override to development mode
    volumes:
      - ./ssr:/app
      - ./frontend/src:/app/frontend/src:ro
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]
