services:
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=landandbay
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=True
      - SECRET_KEY=dev_secret_key_replace_in_production
      - DATABASE_URL=postgresql://landandbay_app:app_password@db:5432/landandbay
      - ALLOWED_HOSTS=localhost,127.0.0.1,app
      - REACT_APP_API_URL=http://localhost:8000/api
      - DB_USERNAME=landandbay_admin
      - DB_PASSWORD=admin_password
      - APP_DB_USERNAME=landandbay_app
      - APP_DB_PASSWORD=app_password
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

volumes:
  postgres_data:
