site_name: Coalition Builder Documentation
site_description: Comprehensive platform for organizing and managing policy advocacy campaigns
site_author: Coalition Builder Team
site_url: https://lhadjchikh.github.io/coalition-builder/

repo_name: coalition-builder
repo_url: https://github.com/lhadjchikh/coalition-builder
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Development: development.md
  - User Guides:
      - Homepage Management: user-guides/homepage-management.md
      - Campaign Management: user-guides/campaign-management.md
      - Stakeholder Management: user-guides/stakeholder-management.md
      - Endorsement Workflow: user-guides/endorsement-workflow.md
      - Content Management: user-guides/content-management.md
  - Deployment: deployment.md
  - Reference:
      - Environment Variables: reference/environment.md
      - CLI Reference: reference/cli.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lhadjchikh/coalition-builder
  version:
    provider: mike

# GitHub Pages specific settings
use_directory_urls: true
