# Generated by Django 5.2.16 on 2026-08-09

from django.db import migrations, models

import coalition.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text=(
                            "Timezone used to display dates and times in the admin site."
                        ),
                        max_length=63,
                        validators=[coalition.core.models.validate_timezone_name],
                    ),
                ),
            ],
            options={
                "verbose_name": "Site configuration",
                "verbose_name_plural": "Site configuration",
            },
        ),
    ]
