# Generated by Django 5.2.3 on 2025-07-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_theme_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="google_fonts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of Google Font family names to load (e.g., ['Merriweather', 'Barlow'])",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="font_size_large",
            field=models.DecimalField(
                decimal_places=3,
                default=1.125,
                help_text="Large font size in rem units",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="font_size_small",
            field=models.DecimalField(
                decimal_places=3,
                default=0.875,
                help_text="Small font size in rem units",
                max_digits=4,
            ),
        ),
    ]
