# Generated by Django 5.2.3 on 2025-07-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_google_fonts_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentblock",
            name="image_author",
            field=models.CharField(
                blank=True,
                help_text="Author/photographer of the image",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="contentblock",
            name="image_license",
            field=models.CharField(
                blank=True,
                help_text="License of the image (e.g., 'CC BY 2.0', 'All rights reserved')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="contentblock",
            name="image_source_url",
            field=models.URLField(
                blank=True,
                help_text="Source URL where the image was obtained",
            ),
        ),
        migrations.AddField(
            model_name="contentblock",
            name="image_title",
            field=models.CharField(
                blank=True,
                help_text="Title of the image for attribution",
                max_length=200,
            ),
        ),
    ]
