# Generated by Django 5.2.4 on 2025-07-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_image_attribution_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentblock",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="favicon_url",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="contentblock",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image for image or text+image blocks",
                null=True,
                upload_to="content_blocks/",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Favicon image",
                null=True,
                upload_to="favicons/",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Organization logo image",
                null=True,
                upload_to="logos/",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_background_image",
            field=models.ImageField(
                blank=True,
                help_text="Hero background image (optional)",
                null=True,
                upload_to="backgrounds/",
            ),
        ),
    ]
