# Generated by Django 5.2.4 on 2025-07-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_contentblock_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="custom_css",
            field=models.TextField(
                blank=True,
                help_text="Additional custom CSS for advanced styling (optional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this theme",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="logo_alt_text",
            field=models.CharField(
                blank=True,
                help_text="Alt text for logo (accessibility)",
                max_length=200,
                null=True,
            ),
        ),
    ]
