# Generated by Django 5.2.4 on 2025-07-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_theme_custom_css_alter_theme_description_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contentblock",
            table="content_block",
        ),
        migrations.AlterModelTable(
            name="homepage",
            table="homepage",
        ),
        migrations.AlterModelTable(
            name="theme",
            table="theme",
        ),
    ]
