# Generated by Django 5.2.1

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geoid", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "abbrev",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Abbreviation for the region (e.g., 'MD', 'CA-12')",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("state", "State"),
                            ("county", "County"),
                            ("congressional_district", "Congressional District"),
                            (
                                "state_senate_district",
                                "State Legislative District - Upper Chamber",
                            ),
                            (
                                "state_house_district",
                                "State Legislative District - Lower Chamber",
                            ),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "coords",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="Internal point",
                        null=True,
                        srid=4326,
                        verbose_name="coordinates",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "geojson",
                    models.JSONField(
                        blank=True,
                        help_text="Simplified geometry suitable for thematic mapping.",
                        null=True,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="regions.region",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.UniqueConstraint(
                fields=("geoid", "type"),
                name="unique__geoid__type",
            ),
        ),
    ]
