# Generated by Django 5.2.4 on 2025-07-10 23:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models

import coalition.stakeholders.constants


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geoid",
                    models.CharField(
                        help_text="Geographic identifier from Census data",
                        max_length=100,
                        db_index=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the region",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Alternative display label for the region",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "abbrev",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Abbreviation for the region (e.g., 'MD', 'CA-12')",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("state", "State"),
                            ("county", "County"),
                            (
                                coalition.stakeholders.constants.DistrictType[
                                    "CONGRESSIONAL"
                                ],
                                "Congressional District",
                            ),
                            (
                                coalition.stakeholders.constants.DistrictType[
                                    "STATE_SENATE"
                                ],
                                "State Senate District",
                            ),
                            (
                                coalition.stakeholders.constants.DistrictType[
                                    "STATE_HOUSE"
                                ],
                                "State House District",
                            ),
                        ],
                        help_text="Type of region (state, county, congressional district, etc.)",
                        max_length=30,
                        db_index=True,
                    ),
                ),
                (
                    "coords",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="Internal point",
                        null=True,
                        srid=4326,
                        verbose_name="coordinates",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        help_text="Full geometry for spatial operations",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "geojson",
                    models.JSONField(
                        blank=True,
                        help_text="Simplified geometry suitable for thematic mapping.",
                        null=True,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent region (e.g., state for a county)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "db_table": "region",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("geoid", "type"),
                        name="unique__geoid__type",
                    ),
                ],
            },
        ),
    ]
