# Generated by Django 5.2.4 on 2025-08-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="abbrev",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Abbreviation for the region (e.g., 'MD', 'CA-12', 'MD-Montgomery')",
                max_length=50,
                null=True,
            ),
        ),
    ]
