# Generated by Django 5.2.4 on 2025-07-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="region",
            table="region",
        ),
    ]
