# Generated by Django 5.2.1 on 2025-06-24 23:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stakeholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                # Required address fields
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zip_code", models.CharField(max_length=10)),
                ("county", models.CharField(blank=True, max_length=100)),
                # Required geographic coordinates
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True,
                        help_text="Latitude and longitude coordinates",
                        srid=4326,
                        spatial_index=True,
                        verbose_name="Geographic Location",
                    ),
                ),
                # District relationships
                (
                    "congressional_district",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "congressional_district"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="congressional_stakeholders",
                        to="regions.region",
                    ),
                ),
                (
                    "state_senate_district",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "state_senate_district"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="state_senate_stakeholders",
                        to="regions.region",
                    ),
                ),
                (
                    "state_house_district",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "state_house_district"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="state_house_stakeholders",
                        to="regions.region",
                    ),
                ),
                # Geocoding timestamp
                ("geocoded_at", models.DateTimeField(auto_now_add=True)),
                # Stakeholder type and metadata
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("farmer", "Farmer"),
                            ("waterman", "Waterman"),
                            ("business", "Business"),
                            ("nonprofit", "Nonprofit"),
                            ("individual", "Individual"),
                            ("government", "Government"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
