# Generated by Django 5.2.4 on 2025-07-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stakeholders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholder",
            name="email_updates",
            field=models.BooleanField(
                default=False,
                help_text="Whether stakeholder opted in to receive policy email updates",
            ),
        ),
    ]
