# Generated by Django 5.2.4 on 2025-07-07 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
        ("stakeholders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stakeholder",
            name="city",
            field=models.CharField(help_text="City or town name", max_length=100),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="congressional_district",
            field=models.ForeignKey(
                blank=True,
                help_text="Congressional district assigned based on address geocoding",
                limit_choices_to={"type": "congressional_district"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="congressional_stakeholders",
                to="regions.region",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="county",
            field=models.CharField(
                blank=True,
                help_text="County name (optional, auto-populated when possible)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when stakeholder record was first created",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="email",
            field=models.EmailField(
                help_text="Primary email address for verification and communication",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="name",
            field=models.CharField(
                help_text="Full name of the individual or primary contact person",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="organization",
            field=models.CharField(
                help_text="Organization or company name (can be same as name for individuals)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="Job title or role within the organization",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="state",
            field=models.CharField(
                help_text="Two-letter state abbreviation (e.g., 'CA', 'NY')",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="state_house_district",
            field=models.ForeignKey(
                blank=True,
                help_text="State house district assigned based on address geocoding",
                limit_choices_to={"type": "state_house_district"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="state_house_stakeholders",
                to="regions.region",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="state_senate_district",
            field=models.ForeignKey(
                blank=True,
                help_text="State senate district assigned based on address geocoding",
                limit_choices_to={"type": "state_senate_district"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="state_senate_stakeholders",
                to="regions.region",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="street_address",
            field=models.CharField(
                help_text="Street address including number and street name",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="type",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("waterman", "Waterman"),
                    ("business", "Business"),
                    ("nonprofit", "Nonprofit"),
                    ("individual", "Individual"),
                    ("government", "Government"),
                    ("other", "Other"),
                ],
                help_text="Category of stakeholder (business, nonprofit, individual, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when stakeholder record was last modified",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="zip_code",
            field=models.CharField(help_text="ZIP or postal code", max_length=10),
        ),
    ]
