# Generated by Django 5.2.1 on 2025-06-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeholder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="type",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("waterman", "Waterman"),
                    ("business", "Business"),
                    ("nonprofit", "Nonprofit"),
                    ("individual", "Individual"),
                    ("government", "Government"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
