# Generated by Django 5.2.4 on 2025-07-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stakeholders", "0002_alter_stakeholder_city_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="stakeholder",
            table="stakeholder",
        ),
    ]
