# Generated by Django 5.2.4 on 2025-08-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholders", "0002_stakeholder_email_updates"),
    ]

    operations = [
        # Add the new fields
        migrations.AddField(
            model_name="stakeholder",
            name="first_name",
            field=models.CharField(
                default="",
                help_text="First name of the individual or primary contact person",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="last_name",
            field=models.CharField(
                default="",
                help_text="Last name of the individual or primary contact person",
                max_length=100,
            ),
        ),
        # Remove the old name field
        migrations.RemoveField(
            model_name="stakeholder",
            name="name",
        ),
    ]
