# Generated by Django 5.2.4 on 2025-08-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholders", "0003_add_first_last_name_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stakeholder",
            name="first_name",
            field=models.CharField(
                help_text="First name of the individual or primary contact person",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="last_name",
            field=models.CharField(
                help_text="Last name of the individual or primary contact person",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="Organization or company name (leave blank for individuals not representing an organization)",
                max_length=200,
            ),
        ),
    ]
