# Generated by Django 5.2.4 on 2025-08-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholders", "0004_make_organization_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stakeholder",
            name="type",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("waterman", "Waterman"),
                    ("business", "Business"),
                    ("nonprofit", "Nonprofit"),
                    ("scientist", "Scientist"),
                    ("healthcare", "Health care professional"),
                    ("government", "Government"),
                    ("individual", "Individual"),
                    ("other", "Other"),
                ],
                help_text="Category of stakeholder (business, nonprofit, individual, etc.)",
                max_length=50,
            ),
        ),
    ]
