# Generated by Django 5.2.4 on 2025-08-19 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0001_initial"),
        ("stakeholders", "0005_add_scientist_healthcare_types"),
    ]

    operations = [
        # Remove old CharField fields
        migrations.RemoveField(
            model_name="stakeholder",
            name="state",
        ),
        migrations.RemoveField(
            model_name="stakeholder",
            name="county",
        ),
        # Add new ForeignKey fields
        migrations.AddField(
            model_name="stakeholder",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="State region",
                limit_choices_to={"type": "state"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="state_stakeholders",
                to="regions.region",
            ),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text="County region (auto-populated based on geocoding)",
                limit_choices_to={"type": "county"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="county_stakeholders",
                to="regions.region",
            ),
        ),
    ]
