
services:
  - type: web
    name: labs-project
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn labs_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: labs-db
          property: connectionString

databases:
  - name: labs-db
