# Generated by Django 5.2.4 on 2025-07-07 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endorsements", "0001_initial"),
        ("stakeholders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endorsement",
            name="stakeholder",
            field=models.ForeignKey(
                help_text="The stakeholder making this endorsement",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endorsements",
                to="stakeholders.stakeholder",
            ),
        ),
    ]
