# Generated by Django 5.2.4 on 2025-07-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endorsements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="endorsement",
            name="terms_accepted",
            field=models.BooleanField(
                default=False, help_text="Whether the terms of use were accepted",
            ),
        ),
        migrations.AddField(
            model_name="endorsement",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True, help_text="When the terms were accepted", null=True,
            ),
        ),
    ]
