# Generated by Django 5.2.4 on 2025-07-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("endorsements", "0002_alter_endorsement_stakeholder"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="endorsement",
            table="endorsement",
        ),
    ]
