# Generated by Django 5.2.4 on 2025-08-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endorsements", "0002_endorsement_terms_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="endorsement",
            name="org_authorized",
            field=models.BooleanField(
                default=False,
                help_text="Whether the stakeholder is authorized to endorse on behalf of their organization",
            ),
        ),
    ]
