# Generated by Django 5.2.4 on 2025-08-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endorsements", "0003_add_org_authorized"),
    ]

    operations = [
        migrations.AddField(
            model_name="endorsement",
            name="display_publicly",
            field=models.BooleanField(
                default=False,
                help_text="Whether admin has approved this endorsement for public display",
            ),
        ),
    ]
