# Generated by Django 5.2.4 on 2025-07-13 19:19

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("endorsements", "0002_endorsement_terms_accepted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("terms", "Terms of Use"),
                            ("privacy", "Privacy Policy"),
                            ("cookies", "Cookie Policy"),
                            ("acceptable_use", "Acceptable Use Policy"),
                        ],
                        help_text="Type of legal document",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the document", max_length=200),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full content of the legal document (HTML allowed)",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version identifier (e.g., '1.0', '2023-12-01')",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the currently active version",
                    ),
                ),
                (
                    "effective_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this version becomes/became effective",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this document was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this document was last updated",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who created this document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_legal_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "legal_document",
                "ordering": ["-effective_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TermsAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the terms were accepted",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which terms were accepted",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser user agent string at time of acceptance",
                    ),
                ),
                (
                    "acceptance_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique token for this acceptance record",
                        unique=True,
                    ),
                ),
                (
                    "endorsement",
                    models.ForeignKey(
                        help_text="The endorsement this acceptance is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_acceptances",
                        to="endorsements.endorsement",
                    ),
                ),
                (
                    "legal_document",
                    models.ForeignKey(
                        help_text="The specific version of the document that was accepted",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="legal.legaldocument",
                    ),
                ),
            ],
            options={
                "db_table": "terms_acceptance",
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(
                fields=["document_type", "is_active"],
                name="legal_docum_documen_27efbc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(
                fields=["effective_date"],
                name="legal_docum_effecti_708624_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="legaldocument",
            unique_together={("document_type", "version")},
        ),
        migrations.AddIndex(
            model_name="termsacceptance",
            index=models.Index(
                fields=["accepted_at"],
                name="terms_accep_accepte_95a0d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="termsacceptance",
            index=models.Index(
                fields=["endorsement", "legal_document"],
                name="terms_accep_endorse_f2d1dd_idx",
            ),
        ),
    ]
