# Generated by Django 5.2.4 on 2025-07-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termsacceptance",
            name="user_agent",
            field=models.CharField(
                blank=True,
                help_text="Browser user agent string at time of acceptance (truncated if over 1000 chars)",
                max_length=1000,
            ),
        ),
    ]
