# Generated by Django 5.2.4 on 2025-07-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0002_limit_user_agent_field_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termsacceptance",
            name="user_agent",
            field=models.CharField(
                blank=True,
                help_text="Browser user agent string (truncated if over 1000 chars)",
                max_length=1000,
            ),
        ),
    ]
