# Generated by Django 5.2.4 on 2025-07-15 13:33

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0003_alter_termsacceptance_user_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldocument",
            name="content",
            field=tinymce.models.HTMLField(
                help_text="Full content of the legal document (HTML allowed)",
            ),
        ),
    ]
