# Generated by Django 5.2.4 on 2025-07-16 18:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0004_alter_legaldocument_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldocument",
            name="content",
            field=tinymce.models.HTMLField(
                help_text="Full content of the legal document (HTML allowed)",
            ),
        ),
    ]
