# Generated by Django 5.2.4 on 2025-07-10 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Legislator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("federal", "Federal"), ("state", "State")],
                        default="federal",
                        help_text="Whether this is a federal or state legislator",
                        max_length=10,
                    ),
                ),
                (
                    "bioguide_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique ID from Congress.gov Bioguide (federal legislators only)",
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "state_id",
                    models.CharField(
                        blank=True,
                        help_text="State-specific legislator ID (state legislators only)",
                        max_length=50,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Legislator's first name",
                        max_length=100,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Legislator's last name",
                        max_length=100,
                    ),
                ),
                (
                    "chamber",
                    models.CharField(
                        choices=[
                            ("house", "U.S. House"),
                            ("senate", "U.S. Senate"),
                            ("state_house", "State House"),
                            ("state_senate", "State Senate"),
                            ("assembly", "State Assembly"),
                            ("house_of_delegates", "House of Delegates"),
                            ("house_of_representatives", "House of Representatives"),
                            ("general_assembly", "General Assembly"),
                        ],
                        help_text="Legislative chamber (e.g., house, senate, state_house)",
                        max_length=25,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="Two-letter state abbreviation",
                        max_length=2,
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        help_text="District number (e.g., '5' or 'At-Large')",
                        max_length=10,
                    ),
                ),
                (
                    "is_senior",
                    models.BooleanField(
                        blank=True,
                        help_text="For senators: True if senior senator, False if junior",
                        null=True,
                    ),
                ),
                (
                    "party",
                    models.CharField(
                        help_text="Political party affiliation (e.g., 'D', 'R', 'I')",
                        max_length=10,
                    ),
                ),
                (
                    "in_office",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the legislator is currently in office",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Official website or legislative profile URL",
                    ),
                ),
                (
                    "state_region",
                    models.ForeignKey(
                        blank=True,
                        help_text="State region for state legislators",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legislators",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legislator",
                "verbose_name_plural": "Legislators",
                "db_table": "legislator",
                "ordering": ["state", "chamber", "last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["level", "state", "chamber"],
                        name="legislator_level_9a93aa_idx",
                    ),
                    models.Index(
                        fields=["bioguide_id"],
                        name="legislator_bioguid_6a5a34_idx",
                    ),
                ],
            },
        ),
    ]
