# Generated by Django 5.2.3 on 2025-06-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Legislator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("federal", "Federal"), ("state", "State")],
                        default="federal",
                        max_length=10,
                    ),
                ),
                (
                    "bioguide_id",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                (
                    "state_id",
                    models.CharField(
                        blank=True,
                        help_text="State-specific legislator ID",
                        max_length=50,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "chamber",
                    models.CharField(
                        choices=[
                            ("house", "U.S. House"),
                            ("senate", "U.S. Senate"),
                            ("state_house", "State House"),
                            ("state_senate", "State Senate"),
                            ("assembly", "State Assembly"),
                            ("house_of_delegates", "House of Delegates"),
                            ("house_of_representatives", "House of Representatives"),
                            ("general_assembly", "General Assembly"),
                        ],
                        max_length=25,
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("district", models.CharField(blank=True, max_length=10)),
                ("is_senior", models.BooleanField(blank=True, null=True)),
                ("party", models.CharField(max_length=10)),
                ("in_office", models.BooleanField(default=True)),
                ("url", models.URLField(blank=True)),
                (
                    "state_region",
                    models.ForeignKey(
                        blank=True,
                        help_text="State region for state legislators",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legislators",
                        to="regions.region",
                    ),
                ),
            ],
        ),
    ]
