# Generated by Django 5.2.3 on 2025-07-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legislators", "0001_initial"),
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legislator",
            options={
                "ordering": ["state", "chamber", "last_name", "first_name"],
                "verbose_name": "Legislator",
                "verbose_name_plural": "Legislators",
            },
        ),
        migrations.AlterField(
            model_name="legislator",
            name="bioguide_id",
            field=models.CharField(
                blank=True,
                help_text="Unique ID from Congress.gov Bioguide (federal legislators only)",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="legislator",
            name="chamber",
            field=models.CharField(
                choices=[
                    ("house", "U.S. House"),
                    ("senate", "U.S. Senate"),
                    ("state_house", "State House"),
                    ("state_senate", "State Senate"),
                    ("assembly", "State Assembly"),
                    ("house_of_delegates", "House of Delegates"),
                    ("house_of_representatives", "House of Representatives"),
                    ("general_assembly", "General Assembly"),
                ],
                help_text="Legislative chamber (e.g., house, senate, state_house)",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="legislator",
            name="district",
            field=models.CharField(
                blank=True,
                help_text="District number (e.g., '5' or 'At-Large')",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="legislator",
            name="first_name",
            field=models.CharField(help_text="Legislator's first name", max_length=100),
        ),
        migrations.AlterField(
            model_name="legislator",
            name="in_office",
            field=models.BooleanField(
                default=True,
                help_text="Whether the legislator is currently in office",
            ),
        ),
        migrations.AlterField(
            model_name="legislator",
            name="is_senior",
            field=models.BooleanField(
                blank=True,
                help_text="For senators: True if senior senator, False if junior",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="legislator",
            name="last_name",
            field=models.CharField(help_text="Legislator's last name", max_length=100),
        ),
        migrations.AlterField(
            model_name="legislator",
            name="level",
            field=models.CharField(
                choices=[("federal", "Federal"), ("state", "State")],
                default="federal",
                help_text="Whether this is a federal or state legislator",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="legislator",
            name="party",
            field=models.CharField(
                help_text="Political party affiliation (e.g., 'D', 'R', 'I')",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="legislator",
            name="state",
            field=models.CharField(
                help_text="Two-letter state abbreviation",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="legislator",
            name="state_id",
            field=models.CharField(
                blank=True,
                help_text="State-specific legislator ID (state legislators only)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="legislator",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Official website or legislative profile URL",
            ),
        ),
        migrations.AddIndex(
            model_name="legislator",
            index=models.Index(
                fields=["level", "state", "chamber"],
                name="legislators_level_776ec9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legislator",
            index=models.Index(
                fields=["bioguide_id"],
                name="legislators_bioguid_5f65e5_idx",
            ),
        ),
    ]
