# Generated by Django 5.2.4 on 2025-07-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legislators", "0002_alter_legislator_options_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="legislator",
            new_name="legislator_level_9a93aa_idx",
            old_name="legislators_level_776ec9_idx",
        ),
        migrations.RenameIndex(
            model_name="legislator",
            new_name="legislator_bioguid_6a5a34_idx",
            old_name="legislators_bioguid_5f65e5_idx",
        ),
        migrations.AlterModelTable(
            name="legislator",
            table="legislator",
        ),
    ]
