# Generated by Django 5.2.4 on 2025-07-15 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentblock",
            name="image_alt_text",
        ),
        migrations.RemoveField(
            model_name="contentblock",
            name="image_author",
        ),
        migrations.RemoveField(
            model_name="contentblock",
            name="image_license",
        ),
        migrations.RemoveField(
            model_name="contentblock",
            name="image_source_url",
        ),
        migrations.RemoveField(
            model_name="contentblock",
            name="image_title",
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(help_text="The image file", upload_to="images/"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or name of the image",
                        max_length=200,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        help_text="Alt text for the image (accessibility)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the image",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="Author/photographer of the image",
                        max_length=200,
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        help_text="License of the image (e.g., 'CC BY 2.0', 'All rights reserved')",
                        max_length=100,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Source URL where the image was obtained",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("general", "General Image"),
                            ("hero", "Hero/Background Image"),
                            ("content", "Content Image"),
                            ("campaign", "Campaign Image"),
                        ],
                        default="general",
                        help_text="Type/category of the image",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this image was uploaded",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this image was last updated",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded this image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "db_table": "image",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image for image or text+image blocks",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_block_images",
                to="content.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Hero background image (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homepage_hero_images",
                to="content.image",
            ),
        ),
    ]
