# Generated by Django 5.2.4 on 2025-07-15 13:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_add_image_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="content",
            field=ckeditor.fields.RichTextField(
                help_text="Main content for this block (text, HTML, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_section_content",
            field=ckeditor.fields.RichTextField(
                help_text="Main content describing the organization's mission and goals",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_content",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Description for how people can get involved",
            ),
        ),
    ]
