# Generated by Django 5.2.4 on 2025-07-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_contentblock_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentblock",
            name="homepage",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="about_section_content",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="about_section_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="contact_phone",
        ),
        migrations.AddField(
            model_name="contentblock",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("homepage", "Homepage"),
                    ("about", "About Page"),
                    ("campaigns", "Campaigns Page"),
                    ("contact", "Contact Page"),
                ],
                default="homepage",
                help_text="Which page this content block appears on",
                max_length=20,
            ),
        ),
    ]
