# Generated by Django 5.2.4 on 2025-07-16 18:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_remove_contentblock_homepage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="content",
            field=tinymce.models.HTMLField(
                help_text="Main content for this block (text, HTML, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="cta_content",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Description for how people can get involved",
            ),
        ),
    ]
