# Generated by Django 5.2.4 on 2025-08-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_homepage_hero_overlay_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentblock",
            name="layout_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Text Left, Image Right"),
                    ("reversed", "Image Left, Text Right"),
                    ("stacked", "Text Above Image"),
                    ("stacked_reversed", "Image Above Text"),
                ],
                default="default",
                help_text="Layout arrangement for Text + Image blocks",
                max_length=20,
            ),
        ),
    ]
