# Generated by Django 5.2.4 on 2025-08-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_add_layout_option_to_contentblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentblock",
            name="vertical_alignment",
            field=models.CharField(
                blank=True,
                choices=[("top", "Top"), ("middle", "Center"), ("bottom", "Bottom")],
                default="middle",
                help_text="Vertical alignment of text relative to image for Text + Image blocks",
                max_length=10,
            ),
        ),
    ]
