# Generated by Django 5.2.4 on 2025-08-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_add_vertical_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentblock",
            name="animation_delay",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Animation delay in milliseconds (0-2000)",
            ),
        ),
        migrations.AddField(
            model_name="contentblock",
            name="animation_type",
            field=models.CharField(
                choices=[
                    ("fade-in", "Fade In"),
                    ("slide-up", "Slide Up"),
                    ("slide-left", "Slide from Left"),
                    ("slide-right", "Slide from Right"),
                    ("scale", "Scale In"),
                    ("none", "No Animation"),
                ],
                default="none",
                help_text="Animation effect when block enters viewport",
                max_length=20,
            ),
        ),
    ]
