# Generated by Django 5.2.4 on 2025-08-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_add_animation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="caption",
            field=models.TextField(
                blank=True,
                help_text="Custom caption/credit text for the image. Can contain HTML including links.",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="caption_display",
            field=models.CharField(
                choices=[
                    ("below", "Below Image"),
                    ("overlay", "Overlay on Image"),
                    ("tooltip", "Tooltip on Hover"),
                    ("none", "Hide Caption"),
                ],
                default="none",
                help_text="How to display the caption/credit",
                max_length=20,
            ),
        ),
    ]
