# Generated by Django 5.2.15 on 2026-08-09

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_add_image_caption_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "slug",
                    models.SlugField(editable=False, max_length=200, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Person Group",
                "verbose_name_plural": "Person Groups",
                "db_table": "person_group",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(editable=False, max_length=200, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("bio", tinymce.models.HTMLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"],
                            ),
                        ],
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("profile_page_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="people",
                        to="content.persongroup",
                    ),
                ),
                (
                    "profile_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_profile_images",
                        to="content.image",
                        verbose_name="profile photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "db_table": "person",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("homepage", "Homepage"),
                    ("about", "About Page"),
                    ("campaigns", "Campaigns Page"),
                    ("contact", "Contact Page"),
                    ("team", "Team Page"),
                ],
                default="homepage",
                help_text="Which page this content block appears on",
                max_length=20,
            ),
        ),
    ]
