# Generated by Django 5.2.4 on 2025-07-10 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("legislators", "0001_initial"),
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Machine-readable name for the campaign",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Public-facing title of the campaign",
                        max_length=200,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Brief summary of the campaign's goals and position",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional context/details about the campaign",
                    ),
                ),
                (
                    "endorsement_statement",
                    models.TextField(
                        blank=True,
                        help_text="The exact statement that endorsers are agreeing to support",
                    ),
                ),
                (
                    "allow_endorsements",
                    models.BooleanField(
                        default=True,
                        help_text="Allow stakeholders to endorse this campaign",
                    ),
                ),
                (
                    "endorsement_form_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Custom instructions shown above the endorsement form",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when campaign was created",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether campaign is active and accepting endorsements",
                    ),
                ),
            ],
            options={
                "db_table": "campaign",
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("federal", "Federal"), ("state", "State")],
                        default="federal",
                        help_text="Whether this is a federal or state bill",
                        max_length=10,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Bill number without prefix (e.g., '123' not 'H.R. 123')",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Official title of the bill",
                        max_length=255,
                    ),
                ),
                (
                    "chamber",
                    models.CharField(
                        choices=[
                            ("house", "U.S. House"),
                            ("senate", "U.S. Senate"),
                            ("state_house", "State House"),
                            ("state_senate", "State Senate"),
                            ("assembly", "State Assembly"),
                            ("house_of_delegates", "House of Delegates"),
                            ("house_of_representatives", "House of Representatives"),
                            ("general_assembly", "General Assembly"),
                        ],
                        help_text="Legislative chamber where bill was introduced",
                        max_length=25,
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        default="119",
                        help_text="Congressional session (e.g., '118') or state session (e.g., '2023-2024')",
                        max_length=20,
                    ),
                ),
                (
                    "introduced_date",
                    models.DateField(help_text="Date the bill was introduced"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="Current status of the bill (e.g., 'In Committee', 'Passed House')",
                        max_length=100,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Link to official bill text or legislative tracking page",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary bill for the campaign",
                    ),
                ),
                (
                    "cosponsors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Cosponsors who have signed onto the bill",
                        related_name="cosponsored_bills",
                        to="legislators.legislator",
                    ),
                ),
                (
                    "related_bill",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related bill in the other chamber",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companion_bills",
                        to="campaigns.bill",
                    ),
                ),
                (
                    "sponsors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Primary sponsors of the bill",
                        related_name="sponsored_bills",
                        to="legislators.legislator",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="State for state-level bills",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bills",
                        to="regions.region",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        help_text="The policy campaign this bill supports",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="campaigns.policycampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
                "db_table": "bill",
                "ordering": ["-introduced_date", "chamber", "number"],
            },
        ),
    ]
