# Generated by Django 5.2.3 on 2025-06-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("legislators", "0001_initial"),
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        help_text="Machine-readable name for the campaign",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional context/details about the campaign",
                    ),
                ),
                (
                    "endorsement_statement",
                    models.TextField(
                        blank=True,
                        help_text="The exact statement that endorsers are agreeing to support",
                    ),
                ),
                (
                    "allow_endorsements",
                    models.BooleanField(
                        default=True,
                        help_text="Allow stakeholders to endorse this campaign",
                    ),
                ),
                (
                    "endorsement_form_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Custom instructions shown above the endorsement form",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("federal", "Federal"), ("state", "State")],
                        default="federal",
                        max_length=10,
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                (
                    "chamber",
                    models.CharField(
                        choices=[
                            ("house", "U.S. House"),
                            ("senate", "U.S. Senate"),
                            ("state_house", "State House"),
                            ("state_senate", "State Senate"),
                            ("assembly", "State Assembly"),
                            ("house_of_delegates", "House of Delegates"),
                            ("house_of_representatives", "House of Representatives"),
                            ("general_assembly", "General Assembly"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        default="119",
                        help_text="Congressional session (e.g., '118') or state session (e.g., '2023-2024')",
                        max_length=20,
                    ),
                ),
                ("introduced_date", models.DateField()),
                ("status", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "cosponsors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cosponsored_bills",
                        to="legislators.legislator",
                    ),
                ),
                (
                    "related_bill",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related bill in the other chamber",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companion_bills",
                        to="campaigns.bill",
                    ),
                ),
                (
                    "sponsors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sponsored_bills",
                        to="legislators.legislator",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="State for state-level bills",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bills",
                        to="regions.region",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="campaigns.policycampaign",
                    ),
                ),
            ],
        ),
    ]
