# Generated by Django 5.2.1 on 2025-06-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policycampaign",
            name="allow_endorsements",
            field=models.BooleanField(
                default=True,
                help_text="Allow stakeholders to endorse this campaign",
            ),
        ),
        migrations.AddField(
            model_name="policycampaign",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Additional context/details about the campaign",
            ),
        ),
        migrations.AddField(
            model_name="policycampaign",
            name="endorsement_form_instructions",
            field=models.TextField(
                blank=True,
                help_text="Custom instructions shown above the endorsement form",
            ),
        ),
        migrations.AddField(
            model_name="policycampaign",
            name="endorsement_statement",
            field=models.TextField(
                blank=True,
                help_text="The exact statement that endorsers are agreeing to support",
            ),
        ),
    ]
