# Generated by Django 5.2.4 on 2025-07-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policycampaign",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Hero image for the campaign displayed on detail page and cards",
                null=True,
                upload_to="campaign_images/",
            ),
        ),
    ]
