# Generated by Django 5.2.3 on 2025-07-04 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
        ("legislators", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={
                "ordering": ["-introduced_date", "chamber", "number"],
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
            },
        ),
        migrations.AlterField(
            model_name="bill",
            name="chamber",
            field=models.CharField(
                choices=[
                    ("house", "U.S. House"),
                    ("senate", "U.S. Senate"),
                    ("state_house", "State House"),
                    ("state_senate", "State Senate"),
                    ("assembly", "State Assembly"),
                    ("house_of_delegates", "House of Delegates"),
                    ("house_of_representatives", "House of Representatives"),
                    ("general_assembly", "General Assembly"),
                ],
                help_text="Legislative chamber where bill was introduced",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="cosponsors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cosponsors who have signed onto the bill",
                related_name="cosponsored_bills",
                to="legislators.legislator",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="introduced_date",
            field=models.DateField(help_text="Date the bill was introduced"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the primary bill for the campaign",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="level",
            field=models.CharField(
                choices=[("federal", "Federal"), ("state", "State")],
                default="federal",
                help_text="Whether this is a federal or state bill",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="number",
            field=models.CharField(
                help_text="Bill number without prefix (e.g., '123' not 'H.R. 123')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="policy",
            field=models.ForeignKey(
                help_text="The policy campaign this bill supports",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="campaigns.policycampaign",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="sponsors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Primary sponsors of the bill",
                related_name="sponsored_bills",
                to="legislators.legislator",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Current status of the bill (e.g., 'In Committee', 'Passed House')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="title",
            field=models.CharField(
                help_text="Official title of the bill",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Link to official bill text or legislative tracking page",
            ),
        ),
    ]
