# Generated by Django 5.2.4 on 2025-07-15 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_policycampaign_image"),
        ("content", "0002_add_image_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policycampaign",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Hero image for the campaign displayed on detail page and cards",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_images",
                to="content.image",
            ),
        ),
    ]
