# Generated by Django 5.2.1 on 2025-06-22 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_add_endorsement_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="policycampaign",
            old_name="slug",
            new_name="name",
        ),
    ]
