# Generated by Django 5.2.4 on 2025-07-16 18:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_policycampaign_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policycampaign",
            name="description",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Additional context/details about the campaign",
            ),
        ),
        migrations.AlterField(
            model_name="policycampaign",
            name="endorsement_form_instructions",
            field=tinymce.models.HTMLField(
                blank=True,
                help_text="Custom instructions shown above the endorsement form",
            ),
        ),
    ]
