# Generated by Django 5.2.4 on 2025-07-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_alter_bill_options_alter_bill_chamber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policycampaign",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Whether campaign is active and accepting endorsements",
            ),
        ),
        migrations.AlterField(
            model_name="policycampaign",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when campaign was created",
            ),
        ),
        migrations.AlterField(
            model_name="policycampaign",
            name="summary",
            field=models.TextField(
                help_text="Brief summary of the campaign's goals and position",
            ),
        ),
        migrations.AlterField(
            model_name="policycampaign",
            name="title",
            field=models.CharField(
                help_text="Public-facing title of the campaign",
                max_length=200,
            ),
        ),
    ]
