# Generated by Django 5.2.4 on 2025-07-15 13:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_update_campaign_image_to_foreignkey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policycampaign",
            name="description",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Additional context/details about the campaign",
            ),
        ),
        migrations.AlterField(
            model_name="policycampaign",
            name="endorsement_form_instructions",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="Custom instructions shown above the endorsement form",
            ),
        ),
    ]
