name: Black

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**/*.py'
      - '.github/workflows/black.yml'
      - 'backend/pyproject.toml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**/*.py'
      - '.github/workflows/black.yml'
      - 'backend/pyproject.toml'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Set up Poetry cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('backend/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd backend
          poetry config virtualenvs.create false
          poetry install --only dev
      
      - name: Run Black
        run: |
          cd backend
          black --check .