name: Frontend Check

on:
  workflow_call: # Allow this workflow to be called by other workflows
  workflow_dispatch:
    inputs:
      ref:
        description: "Git reference to checkout"
        required: false
        default: ""

permissions:
  contents: read
  actions: read # Need actions:read for codecov in called workflows
  id-token: write # For Codecov authentication on protected branches

jobs:
  # Run frontend linting in parallel
  typescript-lint:
    name: TypeScript Lint
    uses: ./.github/workflows/lint_typescript.yml
    permissions:
      contents: read

  prettier-lint:
    name: Prettier Format Check
    uses: ./.github/workflows/lint_prettier.yml
    permissions:
      contents: read

  # Run tests only after both lint checks pass
  frontend-tests:
    name: Frontend Tests
    needs: [typescript-lint, prettier-lint]
    uses: ./.github/workflows/test_frontend.yml
    permissions:
      contents: read
      actions: read # Need actions:read for codecov
      id-token: write # For Codecov authentication on protected branches
    secrets: inherit
