name: JavaScript Linting

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/src/**/*.js'
      - 'frontend/src/**/*.jsx'
      - 'frontend/src/**/*.ts'
      - 'frontend/src/**/*.tsx'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
      - '.github/workflows/js-lint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/src/**/*.js'
      - 'frontend/src/**/*.jsx'
      - 'frontend/src/**/*.ts'
      - 'frontend/src/**/*.tsx'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
      - '.github/workflows/js-lint.yml'
  # Allow manual triggers
  workflow_dispatch:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint JavaScript/JSX files
      run: npm run lint:ci