name: TypeScript Type Check

permissions:
  contents: read

on:
  workflow_call: # Allow this workflow to be called by other workflows

jobs:
  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci || npm ci --legacy-peer-deps
        working-directory: frontend

      # No longer need to setup shared directory since it's been consolidated

      - name: Run frontend TypeScript check
        run: |
          # Run typecheck with the build config that excludes test files
          npx tsc --noEmit -p tsconfig.build.json
        working-directory: frontend


