name: TypeScript Type Check

permissions:
  contents: read

on:
  workflow_call: # Allow this workflow to be called by other workflows

jobs:
  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: |
            frontend/package-lock.json
            ssr/package-lock.json

      - name: Install frontend dependencies
        run: npm ci --no-optional || npm ci --legacy-peer-deps --no-optional
        working-directory: frontend

      - name: Install SSR dependencies
        run: npm ci --no-optional || npm ci --legacy-peer-deps --no-optional
        working-directory: ssr

      - name: Run frontend TypeScript check (includes shared files)
        run: npm run typecheck
        working-directory: frontend

      - name: Run SSR TypeScript check (includes shared files)
        run: npm run typecheck
        working-directory: ssr
