name: TypeScript Type Check

permissions:
  contents: read

on:
  workflow_call: # Allow this workflow to be called by other workflows

jobs:
  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci || npm ci --legacy-peer-deps

      - name: Run TypeScript type check
        run: npm run typecheck
