name: Python Lint

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
      - ".github/workflows/python-lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.py"
      - ".github/workflows/python-lint.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t landandbay:latest .

      - name: Run linters in Docker container
        run: |
          docker run --rm landandbay:latest bash -c "cd /app && black --check . && ruff check ."
