name: Ruff

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**/*.py'
      - '.github/workflows/ruff.yml'
      - 'backend/pyproject.toml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**/*.py'
      - '.github/workflows/ruff.yml'
      - 'backend/pyproject.toml'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd backend
          poetry config virtualenvs.create false
          poetry install --only dev
      
      - name: Run Ruff
        run: |
          cd backend
          ruff check .