name: Frontend Tests (SSR)

on:
  workflow_call: # Allow this workflow to be called by other workflows

# Set explicit permissions for the GITHUB_TOKEN
permissions:
  contents: read # Only need read access to checkout the code

jobs:
  unit-tests:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-unit
          key: ${{ runner.os }}-buildx-unit-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-unit-

      # Build a lightweight image just for frontend unit tests
      - name: Build frontend test image
        run: |
          cd frontend && docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache-unit \
            --cache-to=type=local,dest=/tmp/.buildx-cache-unit-new,mode=max \
            --no-cache-filter=frontend-builder \
            --load \
            --target=frontend-builder \
            -t coalition_frontend_test:latest \
            .

      # Temp fix for cache
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-unit
          mv /tmp/.buildx-cache-unit-new /tmp/.buildx-cache-unit

      - name: Run TypeScript check (TEMPORARILY DISABLED)
        run: |
          echo "TypeScript check temporarily disabled due to module resolution issues in Docker"
          # docker run --rm coalition_frontend_test:latest \
          #   sh -c "npm run typecheck || npm run tsc || echo 'Typecheck not available, skipping'"

      - name: Run lint
        run: |
          docker run --rm coalition_frontend_test:latest \
            sh -c "npm run lint || echo 'Linting not available, skipping'"

      - name: Run unit tests
        run: |
          docker run --rm \
            -e NODE_ENV=test \
            coalition_frontend_test:latest \
            npm test

      - name: Run build
        run: |
          docker run --rm \
            -e NODE_ENV=test \
            -e SKIP_STATIC_GENERATION=true \
            coalition_frontend_test:latest \
            npm run build
