name: TypeScript Type Check

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/src/**/*.ts'
      - 'frontend/src/**/*.tsx'
      - 'frontend/tsconfig.json'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
      - '.github/workflows/ts-typecheck.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/src/**/*.ts'
      - 'frontend/src/**/*.tsx'
      - 'frontend/tsconfig.json'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
      - '.github/workflows/ts-typecheck.yml'
  # Allow manual triggers
  workflow_dispatch:

jobs:
  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci || npm ci --legacy-peer-deps
    
    - name: Run TypeScript type check
      run: npm run typecheck